COLUMNS = {"height": "Height (cm)"}
NAMES = (
    "Timestamp",
    "Sex",
    "Age (years)",
    "Weight (kg)",
    "Height (cm)",
    "Dominant Hand",
    "Sexual Orientation",
    "Gender",
    "Country of Birth",
    "Year of Immigration",
    "Number of Siblings",
    "Placement by Age Among Siblings",
    "City of Residence",
    "Formal Education",
    "Subjects of Academic Degrees",
    "5 pt. Matriculations",
    "Profession",
    "Monthly Income (NIS)",
    "Cultural Descent",
    "First Language",
    "Other Spoken Languages",
    "Relationship Status",
    "Years in Current Relationship",
    "Number of Children",
    "Hobbies",
    "Number of Weekly Workouts",
    "Physical Activities",
    "Cups of Coffee per Day",
    "Cups of Water per Day",
    "Cups of Non-diet Beverages per Day",
    "Diet",
    "Alcohol Consumption (days per week)",
    "Social Meetings per Week",
    "Frequency of Feeling Stress or Anxiety",
    "Principal Source of Anxiety",
    "Anxiety Treatment History",
    "Bedtime",
    "Time Until Falling Asleep (minutes)",
    "Wakeup Time",
    "Hours of Sleep",
    "Not Falling Asleep Within 30 Minutes",
    "Waking up Often or Too Early",
    "Having to Use the Toilet Often During the Night",
    "Problems Breathing Comfortably",
    "Snoring or Coughing",
    "Felt Too Cold During the Night",
    "Felt Too Warm During the Night",
    "Nightmares",
    "Pain During the Night",
    "Other Reasons for Trouble Sleeping",
    "Frequency of Other Reasons Effecting Sleep in Past Month",
    "General Sleep Quality",
    "Sleep Medication Consumption Frequency in Past Month",
    "Trouble Staying Awake",
    "Trouble Maintaining Enthusiasm",
    "Living With Partner",
    "Partner-reported Snoring Frequency",
    "Partner-reported Breathing Problems Frequency",
    "Partner-reported Involuntary Movement Frequency",
    "Partner-reported Waking Disorientation Frequency",
    "Other Sleeping Problems",
    "Other Sleeping Problems Frequency",
    "Blood Sugar Levels",
    "Blood Pressure",
    "Thyroid Function",
    "Cholesterol Levels",
    "Neurological Conditions",
    "Endocrine Disorders",
    "Hematological Disorders",
    "Eye Diseases",
    "Otorhinolaryngological Diseases",
    "Respiratory Diseases",
    "Cardiological Diseases (1)",
    "High Blood Pressure",
    "Gastrointestinal Diseases",
    "Arthritis",
    "Skeletal Diseases",
    "Cancer",
    "Psychological Disorders",
    "Hereditary Disease",
    "Autistic Spectrum Disorder",
    "Attention Deficit Disorder",
    "Diabetes",
    "Chronic Disease Comments",
    "Gallstones",
    "Kidney Stones",
    "Osteoarthritis",
    "Osteoporosis",
    "AIDS",
    "Sexual Impotence",
    "Alzheimer's Disease",
    "Allergies",
    "Anemia",
    "Acne",
    "Nauseousness",
    "Nausea and Vomiting of Pregnancy",
    "Bronchitis",
    "Urinary Incontinence",
    "Intenstinal Gas",
    "Benign Tumors",
    "Menopause",
    "Glaucoma",
    "Gastritis",
    "Depression",
    "Unknown",
    "Otitis",
    "Laryngitis",
    "Urinary Tract Infection",
    "Phlebitis",
    "Hepatitis",
    "Gingivitis",
    "Gastritis (1)",
    "Pneumonia",
    "Benign Prostatic Hypertrophy",
    "Hypoglycemia",
    "Hypothyroidism",
    "Attention Deficit Disorder (1)",
    "Sleep Disorder",
    "Breastfeeding",
    "Obesity",
    "Menstruation",
    "Hemorrhoids",
    "Unknown (1)",
    "High Triglycerides",
    "Multiple Sclerosis",
    "Atherosclerosis",
    "Warts",
    "High Blood Pressure (1)",
    "Ear Pain",
    "Throat Pain",
    "Headache",
    "Back or Muscle Pain",
    "High Cholesterol",
    "Intestinal Ulcers",
    "Lice",
    "Stress",
    "High Blood Pressure (2)",
    "Low Blood Pressure",
    "Epstein–Barr Virus",
    "Cardiological Diseases",
    "Intestinal Infections",
    "Migranes",
    "Immune System Disorders",
    "Sleep Problems",
    "Hair Loss",
    "Seborrhoeic Dermatitis",
    "Diabetes (1)",
    "Sinusitis",
    "Cancer (1)",
    "Constipation",
    "Feet or Nail Fungal Infections",
    "Psoriasis",
    "Mouth Sores",
    "Home Remedies",
    "Celiac Disease",
    "Heartburn",
    "Vaginal Candidiasis",
    "Pityriasis Capitis",
    "Cirrhosis",
    "Gout",
    "Coughing",
    "Herpes Zoster",
    "Diarrhea",
    "Flu",
    "Worms",
    "Carpal Tunnel Syndrome",
    "Premenstrual Syndrome",
    "Nutritional Supplements",
    "Experienced Prolonged Depression",
    "Routine Medication Consumption",
    "Sensitivity to Medication",
    "Food Sensitivities",
    "Undergone Surgery",
    "Consumes Nicotine",
    "Consumes Cannabis",
    "Consumes Other Drugs",
    "Routine Medications",
    "Sensitivity to Medication Information",
    "Frequency of Nicotine Consumption",
    "Frequency of Cannabis Consumption",
    "Smartphone",
    "Computer",
    "Watching Screens",
    "Needs Glasses",
    "Needs Hearing Aid",
    "First Degree Proximity to Alzheimer's or MCI",
    "First Degree Proximity to Parkinson's",
    "First Degree Proximity to Cardiological Disease",
    "First Degree Proximity to Stroke Victim",
    "First Degree Proximity to Cancer Patient",
    "First Degree Proximity to Autoimmune Disease",
    "First Degree Proximity to Gastrointenstinal Disease",
    "First Degree Proximity to Psychiatric Disease",
    "First Degree Proximity to ASD",
    "First Degree Proximity to ADD",
    "First Degree Proximity to Congenital Disease",
    "First Degree Proximity to Diabetes",
    "BFI Q1",
    "BFI Q2",
    "BFI Q3",
    "BFI Q4",
    "BFI Q5",
    "BFI Q6",
    "BFI Q7",
    "BFI Q8",
    "BFI Q9",
    "BFI Q10",
    "BFI Q11",
    "BFI Q12",
    "BFI Q13",
    "BFI Q14",
    "BFI Q15",
    "BFI Q16",
    "BFI Q17",
    "BFI Q18",
    "BFI Q19",
    "BFI Q20",
    "BFI Q21",
    "BFI Q22",
    "BFI Q23",
    "BFI Q24",
    "BFI Q25",
    "BFI Q26",
    "BFI Q27",
    "BFI Q28",
    "BFI Q29",
    "BFI Q30",
    "BFI Q31",
    "BFI Q32",
    "BFI Q33",
    "BFI Q34",
    "BFI Q35",
    "BFI Q36",
    "BFI Q37",
    "BFI Q38",
    "BFI Q39",
    "BFI Q40",
    "BFI Q41",
    "BFI Q42",
    "BFI Q43",
    "BFI Q44",
    "Political Orientation",
    "Economical Orientation",
    "Belief in Equal Rights",
)
REPLACE_DICT = {
    "Dominant Hand": {
        "ימין": "Right",
        "שמאל": "Left",
        "לא מוחלט": "Ambidextrous",
    },
    "Sexual Orientation": {
        "הטרוסקסואל": "Heterosexual",
        "ביסקסואל": "Bisexual",
        "הומוסקסואל": "Homosexual",
        "דמיסקסואל": "Demisexual",
        "סטרייט": "Heterosexual",
        "סטרייטית": "Heterosexual",
        "אסקסואל": "Asexual",
        "פאנסקסואל": "Pansexual",
        "מעדיף לא לענות": None,
    },
    "Sex": {"זכר": "Male", "נקבה": "Female"},
    "Gender": {
        "סיסג'נדר (זכר שמזדהה כגבר \\ נקבה שמזדהה כאישה)": "Cisgender",
        "זכר": "Cisgender",
        "נקבה": "Cisgender",
        "אינני מזוהה עם מגדר מסוים": "Genderless",
        "ג'נדר-פלואיד (הזהות המגדרית שלי אינה קבועה)": "Gender-fluid",
    },
    "Country of Birth": {
        "ישראל": "Israel",
        "ארצות הברית": "USA",
        "פולין": "Poland",
        "צרפת": "France",
        "אוקראינה": "Ukraine",
        "רוסיה": "Russia",
        "מולדובה": "Moldova",
        "אוזבקיסטן": "Uzbekistan",
        "קזחסטאן": "Kazakhstan",
        "ארגנטינה": "Argentina",
        "רומניה": "Romania",
        "ברית המועצות": "Russia",
        "אזרביג'אן": "Azerbaijan",
    },
    "Formal Education": {
        "תואר ראשון": "Bachelor's Degree",
        "תואר שני ומעלה": "Master's Degree or More",
        "על-תיכונית": "Tertiary Education",
        "תיכונית מלאה": "High-School Graduate",
        "תיכונית חלקית": "High-School (partial)",
    },
    "Cultural Descent": {
        "יהודי אשכנזי": "Ashkenazi Jew",
        "יהודי ספרדי": "Sephardic Jew",
        "יהודי ספרדי, יהודי אשכנזי": "Both Ashkenazi and Sephardic Jew",
    },
    "First Language": {
        "עברית": "Hebrew",
        "רוסית": "Russian",
        "ערבית": "Arabic",
        "אנגלית": "English",
        "צרפתית": "French",
        "ספרדית": "Spanish",
        "פולנית": "Polish",
    },
    "Relationship Status": {
        "בזוגיות": "In a relationship",
        "רווק": "Single",
        "גרוש": "Divorced",
        "נשוי": "Married",
        "נשואה": "Married",
    },
    "Diet": {
        "אומניבור (אוכל כל)": "Omnivore",
        "אוכל כל אך ממעיט בבשר": "Omnivore with reduced meat consumption",
        "צמחוני": "Vegetarian",
        "אוכל כל אך מעדיף בשר": "Omnivore with preference to meat",
        "טבעוני": "Vegan",
        "כשר \\ חלאל": "Kosher/Halal",
        "פסקטריין (צמחוני שאוכל דגים)": "Pescatarian",
        "נטול גלוטן": "Gluten-free",
        "פליאו": "Paleolithic",
        "קיטו": "Ketogenic",
    },
    "Frequency of Feeling Stress or Anxiety": {
        "אף פעם": "0 - Never",
        "לעתים רחוקות": "1 - Rarely",
        "לפעמים": "2 - Sometimes",
        "רב הזמן": "3 - Most of the time",
        "כל הזמן": "4 - All the time",
    },
    "Principal Source of Anxiety": {
        "עבודה": "Work",
        "יחסים בין-אישיים": "Inter-personal Relationships",
        "לימודים": "Studying",
        "דברים חיצוניים שקורים בסביבתי": "External Events",
        "משפחה": "Family",
        "בריאות": "Health",
        "משתנה": "Inconsistent Source",
        "לימודים ועבודה": "Working and Studying",
    },
    "Anxiety Treatment History": {"כן": "Yes", "לא": "No"},
    "Frequency of Cannabis Consumption": {
        "כפעם בחודש או פחות": "Once a month or less",
        "כמה פעמים בשבוע": "A few times a month",
        "כפעם בשבוע": "About once a month",
        "יומיומית": "Daily",
    },
    "Blood Sugar Levels": {
        "נורמלי": "1 - Normal",
        "לא נבדק": "N/A",
        "גבוה": "2 - High",
        "נמוך": "0 - Low",
        "נמוך מאוד": "0 - Low",
    },
    "Blood Pressure": {
        "נורמלי": "1 - Normal",
        "לא נבדק": "N/A",
        "גבוה": "2 - High",
        "נמוך": "0 - Low",
        "נמוך מאוד": "0 - Low",
    },
    "Thyroid Function": {
        "נורמלי": "1 - Normal",
        "לא נבדק": "N/A",
        "גבוה": "2 - High",
        "נמוך": "0 - Low",
        "נמוך מאוד": "0 - Low",
    },
    "Cholesterol Levels": {
        "נורמלי": "1 - Normal",
        "לא נבדק": "N/A",
        "גבוה": "2 - High",
        "נמוך": "0 - Low",
        "נמוך מאוד": "0 - Low",
    },
    "Attention Deficit Disorder (1)": {"לא": "No", "כן": "Yes"},
    "Attention Deficit Disorder": {
        "לא": "No",
        "סובל כעת": "Yes",
        "סבלתי בעבר": "Suffered in the past",
    },
}
